# Generated by Django 5.2.14 on 2026-09-02 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('tavsif', models.TextField(verbose_name='Tavsif')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Narx')),
                ('miqdor', models.PositiveIntegerField(default=0, verbose_name='Miqdor')),
                ('holat', models.CharField(default='mavjud', max_length=20, verbose_name='Holat')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('yangilangan', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'db_table': 'mahsulotlar',
                'ordering': ['-yaratilgan'],
            },
        ),
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Nomi')),
                ('muallifi', models.CharField(max_length=100, verbose_name='Muallifi')),
                ('sarlavha', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('maqola_haqida_qisqacha', models.TextField(verbose_name='Mahsulot')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('holat', models.CharField(choices=[('chop_etilmagan', 'Chop Etilmagan'), ('chop_etilgan', 'Chop Etilgan')], default='chop_etilgan', max_length=20, verbose_name='Holat')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('yangilangan', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'db_table': 'maqola',
                'ordering': ['-yangilangan'],
            },
        ),
    ]
