# Generated by Django 5.2.14 on 2026-09-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maqola',
            old_name='nomi',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='maqola',
            old_name='maqola_haqida_qisqacha',
            new_name='tavsif',
        ),
    ]
