# Generated by Django 5.2.14 on 2026-09-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_nomi_maqola_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='surat',
            field=models.ImageField(blank=True, null=True, upload_to='mahsulot', verbose_name='Surat'),
        ),
    ]
