# Generated by Django 5.2.14 on 2026-09-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mahsulot_surat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='brend',
            field=models.CharField(blank=True, default='Brend nomi qoyilmagan.', max_length=100, null=True, verbose_name='Brend'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='ishlab_chiqarilgan',
            field=models.CharField(blank=True, default="o'zbekiston", max_length=100, null=True, verbose_name='Ishlab chiqarilgan'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='tarkibi',
            field=models.TextField(blank=True, default='Tarkibi qoyilmagan.', null=True, verbose_name='Tarkibi'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='yaroqlilik',
            field=models.CharField(blank=True, default='12 oy', max_length=50, null=True, verbose_name='Yaroqlilik'),
        ),
    ]
